name: 'Build'

permissions:
      id-token: write
      contents: read

env:
  AWS_REGION: us-east-1

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch: {}

jobs:
  build:
    name: Build extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build
        uses: xu-cheng/latex-action@v3 # TODO Replace this with a non-bloated action
        with:
          root_file: resume.tex
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::626281517120:role/FilesGlasketS3Role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: Upload
        run: |
          aws s3 cp resume.pdf s3://files.glasket.com/resume.pdf
